#
# ADOBE CONFIDENTIAL
# __________________
#
# Copyright 2019 Adobe Systems Incorporated
# All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Adobe Systems Incorporated and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to Adobe Systems Incorporated and its
# suppliers and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from Adobe Systems Incorporated.
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

ssh_keys: &ssh_keys
  add_ssh_keys:
    fingerprints:
      - "98:db:59:8c:95:ec:31:3b:ad:d4:8e:a7:c5:6d:57:8f"

test_results_build: &test_results_build
  # Unit-Test-reports for modules without action folder
  store_test_results:
    path: build
test_results_ac_build: &test_results_ac_build
  # Test-reports for modules with action folder
  store_test_results:
    path: action/build
test_logs_ac_bld: &test_logs_ac_bld
  # Test-logs for modules with action folder
  store_artifacts:
    path: action/build
    destination: build
test_logs_bld: &test_logs_bld
  # Test-logs for modules without action folder
  store_artifacts:
    path: build
    destination: build  
test_logs_ac_nui: &test_logs_ac_nui
  # Test-logs for modules with action folder for image comparision
  store_artifacts:
    path: action/.nui
    destination: .nui
coverage: &coverage
  # Coverage-report
  store_artifacts:
    path: coverage
    destination: coverage

version: 2

commands:
  artifactory_login: &artifactory_login
    run:
      name: Artifactory credentials setup
      command: |
        curl --fail -s -u${ARTIFACTORY_USER}:${ARTIFACTORY_TOKEN} https://artifactory.corp.adobe.com/artifactory/api/npm/npm-nui-release-local/auth/nui >> ~/.npmrc
        # this was added only for core repo
        curl --fail -s -u${ARTIFACTORY_USER}:${ARTIFACTORY_TOKEN} https://artifactory.corp.adobe.com/artifactory/api/npm/npm-aem-desktop-release-local/auth/aem-desktop >> ~/.npmrc

jobs:
  build_runtime:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *ssh_keys
      - *artifactory_login
      - run:
          name: Creating Docker Runtime
          command: |
            cd ~
            git clone git@git.corp.adobe.com:nui/circleci.git
            cd circleci
            git pull
            cat build_runtime.sh
            ./build_runtime.sh           
      - persist_to_workspace:
          root: /home/circleci/cache/
          paths:
            - docker_runtime

  build:
    working_directory: ~/repo
    machine:
        enabled: true
        docker_layer_caching: true
    steps:
      - checkout:
          path: ~/repo
      - *artifactory_login
      - attach_workspace:
          at: cache
      - run:
          name: Credentials and setup
          command: |
            docker login -u $ARTIFACTORY_UW2_USER -p $ARTIFACTORY_UW2_TOKEN docker-senseiwins-release.dr-uw2.adobeitc.com
            docker login docker-project-nui-snapshot.dr.corp.adobe.com -u $ARTIFACTORY_USER -p $ARTIFACTORY_TOKEN
      - run:
          name: Load Docker Runtime and run npm tests
          command: |
            cd ~
            git clone git@git.corp.adobe.com:nui/circleci.git
            cd circleci
            git pull
            cat build.sh
            ./build.sh
      - *test_results_build
      - *test_results_ac_build
      - *test_logs_ac_bld
      - *test_logs_bld
      - *test_logs_ac_nui
      - *coverage

  dependent-module-tests:
    working_directory: ~/repo
    machine:
        enabled: true
        docker_layer_caching: true
    steps:  
      - checkout
      - *ssh_keys
      - *artifactory_login
      - attach_workspace:
          at: cache
      - run:
          name: Credentials and setup
          command: |
            docker login -u $ARTIFACTORY_UW2_USER -p $ARTIFACTORY_UW2_TOKEN docker-senseiwins-release.dr-uw2.adobeitc.com
            docker login docker-project-nui-snapshot.dr.corp.adobe.com -u $ARTIFACTORY_USER -p $ARTIFACTORY_TOKEN
      - run:
          name: Get dependents, Install and Pack (dependent-module-tests_Step_1.sh)
          command: |
            cd ~
            git clone git@git.corp.adobe.com:nui/circleci.git
            cd circleci
            git pull
            cat dependent-module-tests-step-1.sh
            ./dependent-module-tests-step-1.sh
      - run:
          name: Create Docker Runtime for all dependents (dependent-module-tests_Step_2.sh)
          command: |
            cd ~/circleci
            cat dependent-module-tests-step-2.sh
            ./dependent-module-tests-step-2.sh
      - run:
          name: Run npm tests for all dependents (dependent-module-tests_Step_3.sh)
          command: |
            cd ~/circleci
            cat dependent-module-tests-step-3.sh
            ./dependent-module-tests-step-3.sh
      # Unit-Test-results
      - store_test_results:
          path: /home/circleci/test_logs
      # Test-logs for modules with action folder
      - store_artifacts:
          path: /home/circleci/test_logs
          destination: test_logs

  deploy_app:
    docker:
      - image: circleci/node:12.16.1
    steps:  
      - checkout
      - *ssh_keys
      - *artifactory_login
      - run:
          name: Credentials and setup
          command: |
            echo "${RUNTIME_NAMESPACE_DEV_WSKPROPS}" | base64 -d > ~/.wskprops
            docker login -u $ARTIFACTORY_UW2_USER -p $ARTIFACTORY_UW2_TOKEN docker-senseiwins-release.dr-uw2.adobeitc.com
            # allow user circleci to make global npm installations
            sudo chown -R circleci /usr/local/ && chmod -R u+x+w /usr/local/
      - run:
          name: Get dependents, Install and pack (deploy-app-step-1.sh)
          command: |
            cd ~
            git clone git@git.corp.adobe.com:nui/circleci.git
            cd circleci
            git pull
            cat deploy-app-step-1.sh
            ./deploy-app-step-1.sh
      - run:
          name: Deploy unique integration test environment (deploy-app-step-2.sh)
          command: |
            cd ~/circleci
            cat deploy-app-step-2.sh
            ./deploy-app-step-2.sh
            
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - env-vars


  integration_tests:
      docker:
      - image: circleci/node:12.16.1
        environment:
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          NUI_API_KEY: ${NUI_API_KEY}
          NUI_IT_INTEGRATION_YAML: ${NUI_IT_INTEGRATION_YAML}
          AZURE_STORAGE_KEY: ${AZURE_STORAGE_KEY}
          AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
    
      steps:
        - checkout
        - *artifactory_login
        - *ssh_keys
        - attach_workspace:
            at: workspace
        - run: cat workspace/env-vars >> $BASH_ENV
        - run:
            name: pull integration tests
            command: |
              git clone git@git.corp.adobe.com:nui/integration-tests.git
              cd integration-tests
              git pull
              npm install
              npm test
              echo "Integration test running against $NUI_URL"


  release:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - *ssh_keys
      - *artifactory_login
      - run:
          name: Releasing module - npm publish and create git tags
          command: |
            cd ~
            git clone git@git.corp.adobe.com:nui/circleci.git
            cd circleci
            git pull
            cat release.sh
            ./release.sh
            
      - persist_to_workspace:
          root: ~/tmpDir
          paths:
            - env-vars

  dependent-version-update:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - *ssh_keys
      - *artifactory_login
      - attach_workspace:
          at: tmpDir
      - run: cat tmpDir/env-vars >> $BASH_ENV
      - run:
          name: Create PR for dependent repos to update version
          command: |
            cd ~
            git clone git@git.corp.adobe.com:nui/circleci.git
            cd circleci
            git pull
            cat dependent-version-update.sh
            ./dependent-version-update.sh
              
  validate_config:
    working_directory: ~/validate
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout:
          path: ~/validate/repo
      - run:
          name: compare with central cci config
          command: |
            cd ~/validate
            git clone git@git.corp.adobe.com:nui/circleci.git
            # git clone https://$GITHUB_TOKEN@git.corp.adobe.com/circleci.git
            cd circleci
            git checkout $CIRCLE_BRANCH
            git branch
            #comparing ~/validate/repo/.circleci/config.yml to ~/validate/circleci/config.yml
            cmp -s ~/validate/repo/.circleci/config.yml ~/validate/circleci/config.yml || { echo 'circleci/config.yml not in sync'; exit 1; }

# validate_config job currently not used
workflows:
    version: 2
    build:
        jobs:
        - build_runtime:
            context: nui
        - build:
            requires:
             - build_runtime
            context: nui
        - dependent-module-tests:
            requires:
             - build_runtime
            context: nui
# deploy only if test pass
        - deploy_app:
            requires:
              - build
            context: nui
        - integration_tests:
            requires:
              - deploy_app
            context: nui
        - release:
            requires:
              - build_runtime
              - build
            filters:
              branches:
                only: master
            context: nui
        - hold-dependent-version-update:
            type: approval # requires that an in-app button be clicked by an appropriate member of the project to continue.
            requires:
              - release
        - dependent-version-update:
            requires:
              - hold-dependent-version-update
            context: nui
#        - validate_config:
#            context: nui