#!/bin/bash

set -x

filename=$(basename "$1")
TYPE=`echo  ${filename##*.} | tr '[a-z]' '[A-Z]'`

file "$2" | grep "$TYPE"
if [ $? -ne 0 ]
then
    echo "Rendition not a $TYPE file as expected" 
    exit 1
fi

# Ensure that we have latest version
docker pull docker-project-nui-snapshot.dr.corp.adobe.com/nui/imgtools 

docker run --rm -v `dirname $1`:/a -v `dirname $2`:/b docker-project-nui-snapshot.dr.corp.adobe.com/nui/imgtools ImageDiff  /a/`basename $1` /b/`basename $2` -tolerance 100
