# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16, 10.19, 12.16, 12.19]

    steps:
    - uses: actions/checkout@v2
    - name: Setup unit test environment
      run: sudo apt-get install librsvg2-bin imagemagick
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Log used OS
      run: pwd
    - name: Install aio
      run: npm install @adobe/aio-cli
    - name: Install dependencies (all)
      run: npm install
    - name: Run unit tests
      run: npm test
    - name: Report coverage
      run: npm run report-coverage
